#! /usr/bin/bash

if [ $1 = "stop" ]
then
    pid=$(pgrep -f "python3 ./server.py")
    if [ -z "$pid" ]; then
    echo "Process not found."
    else
    echo "Process found with PID: $pid. Killing process."
    kill $pid
    fi
elif [ $1 = "start" ]
then
    source furlong/bin/activate
    nohup python3 ./server.py > output.txt 2>&1 &
    pid=$!
    echo "Starting on PID: $pid" 
elif [ $1 = 'fg' ]
then
    source furlong/bin/activate
    python3 ./server.py
else
    echo "Unrecognized option. Use 'start' or 'stop' or 'fg'."
fi
